In [4]:

import numpy as np
from mp_api.client import MPRester  # ✅ Correction ici
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from tabulate import tabulate
from pymatgen.io.cif import CifWriter

ImportError: cannot import name 'SymmetryUndeterminedError' from 'pymatgen.symmetry.analyzer' (/home/modl/maurom/.local/lib/python3.9/site-packages/pymatgen/symmetry/analyzer.py)

In [12]:
from pymatgen.core import Lattice, Structure
print("Téléchargement du fichier CIF...")

API_KEY = "23hOiKlEoGQW353WjxM4GcQtg20eKzYt"  # Remplacez par votre clé API

with MPRester(API_KEY) as mpr:
    structure = mpr.materials.get_structure_by_material_id("mp-10969")  # Nouvelle API v2
    CifWriter(structure).write_file("CdCN2_mp-10969_symmetrized.cif")  # Écriture du fichier CIF

print("Fichier CIF téléchargé avec succès !")


coords = [[0.0, 0.0, 0.0], [2/3,1/3,5/6],[2/3,1/3,0.9177]]
lattice = Lattice.from_parameters(a=5.28, b=5.28, c=5.28, alpha=39.40,
                                  beta=39.40, gamma=39.40)
struct = Structure(lattice, ["Cd", "C","N"], coords)
view = JsmolView.from_file("CdCN2_mp-7173_symmetrized.cif", "{3 3 3}")
display(view)

Téléchargement du fichier CIF...


AttributeError: materials is not an attribute of this implementation of MPRester, which only supports functionalityused by 80% of users. If you are looking for the full functionality MPRester, pls install the mp-api .

In [22]:
customSym1 = SymmOp.from_xyz_str('-x, -y, -z')
customSym2 = SymmOp.from_xyz_str('-x, y, z')
customSym3 = SymmOp.from_xyz_str('-x,y, z')

In [23]:
Cd = [0.0,0.0,0.0]
C = [2/3,1/3,5/6]
N = [2/3,1/3,0.9177]

In [24]:
Cdres = customSym1.operate(Cd)
Cres = customSym2.operate(C)
Nres = customSym3.operate(N)

On va maintenant appliquer 3 symétries différentes ( 1 pour chaque atome ).
La première opération est une simple inversion du Scandium. La deuxième consiste en une roto-réflexion S2 de l'Antimoine, c'est à dire une rotation d'ordre 2 autour de l'axe z suivie d'une réflexion par le plan y=0. Enfin, la dernière est une réflexion par le plan x=0 de l'atome de Platine.

In [25]:
print("\n")
print(tabulate([
	["On applique une inversion "+"("+str(customSym1.as_xyz_str()+")"),str(Sc),str(Scres)],
	["----------------------------------","",""],
	[customSym1,"",""],
	["----------------------------------","-----------------","----------------------------------"],
	["On applique une roto-réflexion S2 "+"("+str(customSym2.as_xyz_str()+")"),str(Sb),str(Sbres)],
	["----------------------------------","",""],	
	[customSym2,"",""],
	["----------------------------------","-----------------","----------------------------------"],
	["On applique une réflexion "+"("+str(customSym3.as_xyz_str()+")"),str(Pt),str(Ptres)],
	["----------------------------------","",""],	
	[customSym3,"",""],
	["----------------------------------","-----------------","----------------------------------"]],
	headers=["Opération de symétrie","Atome de départ","Atome d'arrivée"]))
print("\n")



Opération de symétrie                         Atome de départ     Atome d'arrivée
--------------------------------------------  ------------------  ----------------------------------
On applique une inversion (-x, -y, -z)        [0.5, 0.5, 0.5]     [-0.5 -0.5 -0.5]
----------------------------------
Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
----------------------------------            -----------------   ----------------------------------
On applique une roto-réflexion S2 (-x, y, z)  [0.0, 0.0, 0.0]     [0. 0. 0.]
----------------------------------
Rot:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
----------------------------------            -----------------   ----------------------------------
On applique une réflexion (-x, y, z)          [0.25, 0.25, 0.25]  [-0.25  0.25  0.25]
----------------------------------
Rot:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
----------------------------------            ----------------- 