In [44]:
import numpy as np
from pymatgen.ext.matproj import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from jupyter_jsmol import JsmolView


In [49]:
print("Téléchargement du fichier CIF...")
structure = MPRester("XOCzg18zLbitVQMZilg0OGK9MJ5rjMXh").get_structure_by_material_id("mp-7173")
CifWriter(structure,0.1, write_magmoms=False).write_file("ScSbPt_mp-7173_symmetrized.cif")
print("Téléchargement terminé !")
view = quick_view(structure)
display(view)

Téléchargement du fichier CIF...


Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Téléchargement terminé !


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [46]:
customSym1 = SymmOp.from_xyz_str('-x, -y, -z')
customSym2 = SymmOp.from_xyz_str('y, x, -z')
customSym3 = SymmOp.from_xyz_str('x, x-y, z')

In [47]:
Sc = [0.5,0.5,0.5]
Sb = [0.0,0.0,0.0]
Pt = [0.25,0.25,0.25]

In [48]:
Scres = customSym1.operate(Sc)
Sbres = customSym2.operate(Sb)
Ptres = customSym3.operate(Pt)

On va maintenant appliquer 3 symétries différentes ( 1 pour chaque atome ).
La première opération est une simple inversion du Scandium. La deuxième consiste en une roto-réflexion de l'Antimoine, c'est à dire une rotation d'ordre 2 autour de l'axe y suivie d'une réflexion par le plan bissecteur du plan z=0. Enfin, la dernière est une réflexion par le plan x'=x/2 de l'atome de Platine.

In [43]:
print("\n")
print(tabulate([
	["On applique une inversion "+"("+str(customSym1.as_xyz_str()+")"),str(Sc),str(Scres)],
	["----------------------------------","",""],
	[customSym1,"",""],
	["----------------------------------","-----------------","----------------------------------"],
	["On applique une roto-réflexion "+"("+str(customSym2.as_xyz_str()+")"),str(Sb),str(Sbres)],
	["----------------------------------","",""],	
	[customSym2,"",""],
	["----------------------------------","-----------------","----------------------------------"],
	["On applique une réflexion "+"("+str(customSym3.as_xyz_str()+")"),str(Pt),str(Ptres)],
	["----------------------------------","",""],	
	[customSym3,"",""],
	["----------------------------------","-----------------","----------------------------------"]],
	headers=["Opération de symétrie","Atome de départ","Atome d'arrivée"]))
print("\n")



Opération de symétrie                      Atome de départ     Atome d'arrivée
-----------------------------------------  ------------------  ----------------------------------
On applique une inversion (-x, -y, -z)     [0.5, 0.5, 0.5]     [-0.5 -0.5 -0.5]
----------------------------------
Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
----------------------------------         -----------------   ----------------------------------
On applique une roto-réflexion (y, x, -z)  [0.0, 0.0, 0.0]     [0. 0. 0.]
----------------------------------
Rot:
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
----------------------------------         -----------------   ----------------------------------
On applique une réflexion (x, x-y, z)      [0.25, 0.25, 0.25]  [0.25 0.   0.25]
----------------------------------
Rot:
[[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
----------------------------------         -----------------   -------------------------