In [1]:
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter
from pymatgen.symmetry.analyzer import *
from pymatgen.io.cif import *
from pymatgen.core.operations import *
from tabulate import tabulate
from pymatgen.symmetry.site_symmetries import *
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import itertools
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pymatgen.symmetry.bandstructure import HighSymmKpath
from pymatgen.core.operations import SymmOp

In [2]:
print("Téléchargement du fichier CIF...")
structure = MPRester("XOCzg18zLbitVQMZilg0OGK9MJ5rjMXh").get_structure_by_material_id("mp-7173")
CifWriter(structure,0.1, write_magmoms=False).write_file("ScSbPt_mp-7173_symmetrized.cif")
print("Téléchargement terminé !")

Téléchargement du fichier CIF...


Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Téléchargement terminé !


In [3]:
customSym1 = SymmOp.from_xyz_str('-x, -y, -z')
customSym2 = SymmOp.from_xyz_str('y, x, -z')
customSym3 = SymmOp.from_xyz_str('x, x-y, z')

In [4]:
Sc = [0.5,0.5,0.5]
Sb = [0.0,0.0,0.0]
Pt = [0.25,0.25,0.25]

In [5]:
Scres = customSym1.operate(Sc)
Sbres = customSym2.operate(Sb)
Ptres = customSym3.operate(Pt)

In [6]:
print("\n")
print(tabulate([
	["("+str(customSym1.as_xyz_str()+")"),str(Sc),str(Scres)],
	["----------------------------------","",""],
	[customSym1,"",""],
	["----------------------------------","-----------------","----------------------------------"],
	["("+str(customSym2.as_xyz_str()+")"),str(Sb),str(Sbres)],
	["----------------------------------","",""],	
	[customSym2,"",""],
	["----------------------------------","-----------------","----------------------------------"],
	["("+str(customSym3.as_xyz_str()+")"),str(Pt),str(Ptres)],
	["----------------------------------","",""],	
	[customSym3,"",""],
	["----------------------------------","-----------------","----------------------------------"]],
	headers=["Opération de symétrie","Atome de départ","Atome d'arrivée"]))
print("\n")



Opération de symétrie               Atome de départ     Atome d'arrivée
----------------------------------  ------------------  ----------------------------------
(-x, -y, -z)                        [0.5, 0.5, 0.5]     [-0.5 -0.5 -0.5]
----------------------------------
Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
----------------------------------  -----------------   ----------------------------------
(y, x, -z)                          [0.0, 0.0, 0.0]     [0. 0. 0.]
----------------------------------
Rot:
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
----------------------------------  -----------------   ----------------------------------
(x, x-y, z)                         [0.25, 0.25, 0.25]  [0.25 0.   0.25]
----------------------------------
Rot:
[[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
----------------------------------  -----------------   ----------------------------------


