In [15]:
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter
from pymatgen.symmetry.analyzer import *
from pymatgen.io.cif import *
from pymatgen.core.operations import *
from tabulate import tabulate
from pymatgen.symmetry.site_symmetries import *
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import itertools
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pymatgen.symmetry.bandstructure import HighSymmKpath
from pymatgen.core.operations import SymmOp

In [16]:
print("Téléchargement du fichier CIF...")
structure = MPRester("XOCzg18zLbitVQMZilg0OGK9MJ5rjMXh").get_structure_by_material_id("mp-7173")
CifWriter(structure,0.1, write_magmoms=False).write_file("RbLaS2_mp-9361_symmetrized.cif")
print("Téléchargement terminé !")

Téléchargement du fichier CIF...


Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Téléchargement terminé !


In [17]:
customSym1 = SymmOp.from_xyz_str('-x, -y, -z')
customSym2 = SymmOp.from_xyz_str('y, x, -z')
customSym3 = SymmOp.from_xyz_str('x, x-y, z')

In [23]:
Rb0 = [0.0,0.0,0.0]
La1 = [0.0,0.5,0.0]
S2 = [0.75,0.25,0.75]

In [24]:
Rb0res = customSym1.operate(Rb0)
La1res = customSym2.operate(La1)
S2res = customSym3.operate(S2)

In [25]:
print("\n")
print(tabulate([
	["("+str(customSym1.as_xyz_str()+")"),str(Rb0),str(Rb0res)],
	["----------------------------------","",""],
	[customSym1,"",""],
	["----------------------------------","-----------------","----------------------------------"],
	["("+str(customSym2.as_xyz_str()+")"),str(La1),str(La1res)],
	["----------------------------------","",""],	
	[customSym2,"",""],
	["----------------------------------","-----------------","----------------------------------"],
	["("+str(customSym3.as_xyz_str()+")"),str(S2),str(S2res)],
	["----------------------------------","",""],	
	[customSym3,"",""],
	["----------------------------------","-----------------","----------------------------------"]],
	headers=["Opération de symétrie","Atome de départ","Atome d'arrivée"]))
print("\n")



Opération de symétrie               Atome de départ     Atome d'arrivée
----------------------------------  ------------------  ----------------------------------
(-x, -y, -z)                        [0.0, 0.0, 0.0]     [0. 0. 0.]
----------------------------------
Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
----------------------------------  -----------------   ----------------------------------
(y, x, -z)                          [0.0, 0.5, 0.0]     [0.5 0.  0. ]
----------------------------------
Rot:
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
----------------------------------  -----------------   ----------------------------------
(x, x-y, z)                         [0.75, 0.25, 0.75]  [0.75 0.5  0.75]
----------------------------------
Rot:
[[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
----------------------------------  -----------------   ----------------------------------


